Mobiles/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from .views import *

app_name = 'Mobiles'

urlpatterns = [
    path('oneplus', oneplus, name = 'oneplus'),
    path('redmi9power', redmi9power, name = 'redmi9power'),
    path('samsunggalaxym51', samsunggalaxym51, name = 'samsunggalaxym51'),
    path('iphone12mini', iphone12mini, name = 'iphone12mini'),
    path('nokia3.4', nokia34, name = 'nokia3.4'),
    path('vivoy20', vivoy20, name = 'vivoy20'),
]

Register_Login/urls.py
from django.conf.urls import include
from django.urls import path
from . import views as login_views

app_name = 'Register_Login'

urlpatterns = [
    path('register', login_views.register, name='register'),
    path('login', login_views.user_login, name='user_login'),
    path('logout', login_views.user_logout, name='user_logout'),
]

Shoptastic/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from Dashboard.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('', include('Dashboard.urls')),
    path('register_login/', include('Register_Login.urls')),
    path('mobile/', include('Mobiles.urls')),
    path('furniture/', include('Furniture.urls')),
    path('clothing/', include('Clothing.urls')),
]

Register_Login/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    uid = models.CharField(max_length=10)

Register_Login/forms.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username', 'email', 'password', 'first_name', 'last_name')

Register_Login/views.py
from django.shortcuts import render
from .forms import UserForm
from django.contrib.auth.models import User
from .models import *


from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout

# Create your views here.
def index(request):
    return render(request, 'Register_Login/index.html')

def register(request):
    registered = False
    first_name = ''
    last_name = ''
    email = ''
    username = ''
    password = ''
    if request.method == "POST":
        user_form = UserForm(data=request.POST)

        if user_form.is_valid():
            # print(User.objects.get(username=request.POST.get('username')).exists())
            user = user_form.save()
            user.set_password(user.password)        # Hashing the passwords -> Encrypting them
            user.save()
            length = len(Customer.objects.all())
            customer = Customer.objects.create(uid='CUS' + str(length + 1), user=user)
            customer.save()
            registered = True
            if user.is_authenticated:
                return HttpResponseRedirect(reverse('Register_Login:user_login'))
        else:
            errors = [(k, v[0]) for k, v in user_form.errors.items()]
            # print(errors[0][1])
            print(errors)
            for i in errors:
                print(f'i = {i[0]}, first_name = {first_name}, last_name = {last_name}, email = {email}, username = {username}, password = {password}')
                if i[0] == 'first_name':
                    first_name = i[1]
                if i[0] == 'last_name':
                    last_name = i[1]
                if i[0] == 'email':
                    email = i[1]
                if i[0] == 'username':
                    username = i[1]
                if i[0] == 'password':
                    password = i[1]
            # print(f'Error = {user_form.errors}')
    else:
        user_form = UserForm()

    return render(request, 'Register_Login/register.html', {'user_form': user_form, 'registered': registered, 'first_name': first_name, 'last_name': last_name, 'email': email, 'username': username, 'password': password})

def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            return HttpResponseRedirect(reverse('index'))
        else:
            print("Someone tried to login and failed")
            print(f'Username: {username} and Password: {password}')
            return HttpResponse("Invalid login details supplied")
    return render(request, 'Register_Login/login.html', {})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

templates/Register_Login/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!--Bootsrap 4 CDN-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!--Fontawesome CDN-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

    <!--Custom styles-->
    <link rel="stylesheet" type="text/css" href="{% static 'Register_Login/css/styles.css' %}">
</head>

<body>
    <div class="container">
        <!-- {% block body_block %}
        {% endblock %} -->
        <div class="d-flex justify-content-center h-100">
            <div class="card">
                <div class="card-header">
                    {% block heading %}
                    {% endblock %}
                    <div class="d-flex justify-content-end social_icon">
                        <span><i class="fab fa-facebook-square"></i></span>
                        <span><i class="fab fa-google-plus-square"></i></span>
                        <span><i class="fab fa-twitter-square"></i></span>
                    </div>
                </div>
                <div class="card-body">
                    {% block form %}
                    {% endblock %}
                </div>
                <div class="card-footer">
                    {% block register_login %}
                    {% endblock %}
                    {% block forgot_password %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'Register_Login/js/app.js' %}"></script>
</body>
</html>

templates/Register_Login/login.html
{% extends 'Register_Login/base.html' %}
{% load static %}

{% block title %}
    Login
{% endblock %}

{% block heading %}
    <h3>Sign In</h3>
{% endblock %}

{% block form %}
    <form action="{% url 'Register_Login:user_login' %}" method="post">
        {% csrf_token %}
        <div class="input-group form-group">
            <div class="input-group-prepend">
                <span class="input-group-text"><i class="fas fa-user"></i></span>
            </div>
            <input type="text" name="username" class="form-control" placeholder="username">

        </div>
        <div class="input-group form-group">
            <div class="input-group-prepend">
                <span class="input-group-text"><i class="fas fa-key"></i></span>
            </div>
            <input type="password" name="password" class="form-control" placeholder="password">
        </div>
        <div class="row align-items-center remember">
            <input type="checkbox">Remember Me
        </div>
        <div class="form-group">
            <input type="submit" value="Login" class="btn float-right login_btn">
        </div>
    </form>
{% endblock %}

{% block register_login %}
    <div class="d-flex justify-content-center links">
        Don't have an account?<a href="{% url 'Register_Login:register' %}">Sign Up</a>
    </div>
{% endblock %}

{% block forgot_password %}
    <div class="d-flex justify-content-center links">
        <a href="#">Forgot your password?</a>
    </div>
{% endblock %}

templates/Register_Login/register.html
{% extends 'Register_Login/base.html' %}
{% load static %}

{% block title %}
    Register
{% endblock %}

{% block heading %}
    <h3>Sign Up</h3>
{% endblock %}

{% block form %}
    <form autocomplete="off" style="height: 300px;" method="POST">
        {% csrf_token %}
        <!-- {{ user_form.as_p }} -->
        <div class="input-group form-group">
            <div class="input-group-prepend">
                <span class="input-group-text"><i class="fas fa-user"></i></span>
            </div>
            <input type="text" class="form-control" placeholder="First name" name="first_name">
        </div>
        <p style="color: yellow;">{{ first_name }}</p>
        <div class="input-group form-group">
            <div class="input-group-prepend">
                <span class="input-group-text"><i class="fas fa-user"></i></span>
            </div>
            <input type="text" class="form-control" placeholder="Last Name" name="last_name">
        </div>
        <p style="color: yellow;">{{ last_name }}</p>
        <div class="input-group form-group">
            <div class="input-group-prepend">
                <span class="input-group-text"><i class="fas fa-envelope"></i></span>
            </div>
            <input type="email" class="form-control" placeholder="E-Mail" name="email">
        </div>
        <p style="color: yellow;">{{ email }}</p>
        <div class="input-group form-group">
            <div class="input-group-prepend">
                <span class="input-group-text"><i class="fas fa-user"></i></span>
            </div>
            <input type="text" class="form-control" placeholder="Username" name="username">
        </div>
        <p style="color: yellow;">{{ username }}</p>
        <div class="input-group form-group">
            <div class="input-group-prepend">
                <span class="input-group-text"><i class="fas fa-key"></i></span>
            </div>
            <input type="password" class="form-control" placeholder="Password" name="password">
        </div>
        <p style="color: yellow;">{{ password }}</p>
        <div class="form-group">
            <input id="register" type="submit" value="Register" class="btn float-right login_btn">
        </div>
    </form>
{% endblock %}

{% block register_login %}
    <div class="d-flex justify-content-center links">
        Already have an account?<a href="{% url 'Register_Login:user_login' %}">Sign In</a>
    </div>
{% endblock %}