Dashboard/urls.py
from django.conf.urls import include
from django.urls import path
from . import views

app_name = 'Dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
]

Mobiles/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from .views import *

app_name = 'Mobiles'

urlpatterns = [
    path('oneplus', oneplus, name = 'oneplus'),
    path('redmi9power', redmi9power, name = 'redmi9power'),
    path('samsunggalaxym51', samsunggalaxym51, name = 'samsunggalaxym51'),
    path('iphone12mini', iphone12mini, name = 'iphone12mini'),
    path('nokia3.4', nokia34, name = 'nokia3.4'),
    path('vivoy20', vivoy20, name = 'vivoy20'),
]

Register_Login/urls.py
from django.conf.urls import include
from django.urls import path
from . import views as login_views

app_name = 'Register_Login'

urlpatterns = [
    path('register', login_views.register, name='register'),
    path('login', login_views.user_login, name='user_login'),
    path('logout', login_views.user_logout, name='user_logout'),
]

Shoptastic/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from Dashboard.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('', include('Dashboard.urls')),
    path('register_login/', include('Register_Login.urls')),
    path('mobile/', include('Mobiles.urls')),
    path('furniture/', include('Furniture.urls')),
    path('clothing/', include('Clothing.urls')),
]

templates/navbar.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>{% block title %}{% endblock %}</title>
  <meta name="viewport" content="width=device-width , initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'Dashboard/css/styles.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
  {% block head_block %}
  {% endblock %}
</head>

<body id="top" class="">

  <header>
    <nav class=" navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <!--brand, search-->
        <div class="row">
          <div class=" navbar-header">
            <button type="button" data-toggle="collapse" data-target="#bar" class="navbar-toggle">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <a class=" navbar-brand" href="{% url 'Dashboard:index' %}">
            <h1 id="head">Shoptastic</h1>
          </a>

          <div class="hidden-xs search pull-left input-group">
            <!--All button-->

            <div class="input-group-btn search-panel">
              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                <span id="search-content">All </span>
                <span class="caret"></span>
              </button>

              <ul class=" dropdown-menu" role="menu">
                <li><a href="#all">All Categories</a></li>
                <li><a href="#x">Mobiles</a></li>
                <li><a href="#y">Furnitures</a></li>
                <li><a href="#z">Men's Wear</a></li>
                <li><a href="#a">Women's Wear</a></li>
                <li><a href="#a">Kids' Wear</a></li>
              </ul>

            </div>
            <input type="hidden" value="all">
            <input type="text" class="form-control" placeholder="Search">
            <span class="input-group-btn">
              <button type="button" class="sub btn btn-default"> <span class=" glyphicon glyphicon-search"></span>

              </button>
            </span>
          </div>
          <div class="visible-xs small">
            <a href=#search><span data-toggle="tooltip" data-placement="bottom" title="Search" class="rt white glyphicon glyphicon-search"></span></a>
            <a href=#address><span data-toggle="tooltip" data-placement="bottom" title="Address" class="rt white glyphicon glyphicon-map-marker"></span></a>
            <a href=#cart><span data-toggle="tooltip" data-placement="bottom" title="Cart" class="rt white glyphicon glyphicon-shopping-cart"></span></a>
          </div>
        </div>

        <div class="navbar-collapse collapse" id="bar">
            <!-- Deliver to and Shop by Category -->
            <ul class="nav navbar-nav navbar-left">

                <!-- Deliver to -->
                <li class="hidden-xs deli">
                <div class="location">
                    <a href="#address"> <span class=" white glyphicon glyphicon-map-marker"></span>
                    <span class="grey">Deliver to</span>
                    <div class="white bold">Srinagar-190006</div>
                    </a>
                </div>
                </li>

                <!-- Shop by Category -->
                <li>
                <div class="dropdown show">
                    <button class="hidden-xs dropbtn dropdown-toggle" data-toggle="dropdown">
                    <span class="grey">Shop by </span>
                    <div>
                        <span class="white bold">Category</span>
                        <span class="grey caret"></span>
                    </div>
                    </button>

                    <div class="dropdown-content">
                    <a href="#">Mobiles</a>
                    <a href="#">Furniture</a>
                    <a href="#">Clothing</a>
                    </div>
                    <!--hamburger-->
                    <div class="visible-xs container">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                        <h5 class="center  panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapse1">
                            Shop by category</a>
                        </h5>
                        </div>
                    </div>
                    </div>
                    <!--hamburger end-->
                </div>
                </li>
            </ul>

            <!-- Sign In, Try Prime, Your Lists, and Cart -->
            <ul class="nav navbar-nav navbar-right">

                <!-- Sign In -->
                <li class="">
                    <div class="dropdown show">
                        <button class="hidden-xs dropbtn dropdown-toggle" data- toggle="dropdown">
                        <span class="grey">Hello,</span>
                        <div>
                            <!-- {% block sign_in %}
                            {% endblock %} -->
                            {% if user.is_authenticated %}
                              <span class="white bold" id="visible">
                                {{ user.get_username }}
                                <a id="hidden" href="{% url 'Register_Login:user_logout' %}">Logout</a>
                              </span>
                              <style>
                                  #visible:hover #hidden {
                                      display: block;
                                      color: white;
                                      position: absolute;
                                  }
                              </style>
                            {% else %}
                              <a href="{% url 'Register_Login:user_login' %}" class="hover-ele">
                                  <span class="white bold" id="visible">
                                      Sign In
                                    <a id="hidden" href="{% url 'Register_Login:user_logout' %}">Logout</a>
                                  </span>
                              </a>
                            {% endif %}
                        </div>
                        </button>
                        <!--hamburger-->
                        <div class="visible-xs container">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                            <h5 class="center  panel-title">
                                <a data-toggle="collapse" data-parent="#accordion" href="{% url 'Register_Login:user_login' %}">
                                Hello, 
                                <!-- {% block sign_in1 %}
                                {% endblock %} -->
                                {% if user.is_authenticated %}
                                  {{ user.get_username }}
                                {% else %}
                                    Sign In
                                {% endif %}
                              </a>
                            </h5>
                            </div>

                            <div id="collapse2" class="panel-collapse collapse ">
                            </div>
                        </div>
                        </div>
                        <!--hamburger end-->
                    </div>
                </li>

                <!-- Your Orders -->
                <li class="">
                    <div class="dropdown show ">
                        <button class="hidden-xs dropbtn dropdown-toggle" data-toggle="dropdown">
                        <span class="grey">Your</span>
                        <div>
                            <span class="white bold">Orders</span>
                        </div>
                        </button>
                        <!--hamburger-->
                        <div class="visible-xs container">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h5 class="center  panel-title">
                                    <a data-toggle="collapse" data-parent="#accordion" href="#collapse3">
                                    Your Orders</a>
                                </h5>
                            </div>

                            <div id="collapse3" class="panel-collapse collapse ">
                            </div>
                        </div>
                        </div>
                        <!--hamburger end-->
                    </div>
                </li>

                <!-- Your Lists -->
                <li class="">
                    <div class="dropdown show ">
                        <button class="hidden-xs dropbtn dropdown-toggle" data-toggle="dropdown">
                        <span class="grey">Your</span>
                        <div>
                            <span class="white bold">Lists</span>
                        </div>
                        </button>
                        <!--hamburger-->
                        <div class="visible-xs container">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                            <h5 class="center  panel-title">
                                <a data-toggle="collapse" data-parent="#accordion" href="#collapse4">
                                Your Lists</a>
                            </h5>
                            </div>
                        </div>
                        </div>
                        <!--hamburger end-->
                    </div>
                </li>

                <!-- Cart -->
                <li class="hidden-xs">
                    <a href="#cart">
                        <div>
                        <span class="bold white glyphicon glyphicon-shopping-cart"></span>
                        <span class="white bold">Cart</span>
                        </div>
                    </a>
                </li>
            </ul>
        </div>
      </div>
    </nav>
  </header>

  {% block body_block %}
  {% endblock %}
  <script src="{% static 'Dashboard/js/app.js' %}" charset="utf-8"></script>

</body>

<footer>
  <div class="bot container-fluid">
    <a href=#top>
      <h4 class="less white">Back to top</h4>
    </a>
  </div>
  <div class="container-fluid">
    <div class="container">
      <div class="row" style="margin-top: 2%; margin-left: 15%;">
        <div class="col-sm-3">
          <h4 class="white">Get to Know Us</h4>
          <div class="gap">
            <a class="grey foot" href="{% url 'Dashboard:about' %}">About Us</a>
          </div>
        </div>
        <div class="col-sm-3">
          <h4 class="white">Connect with Us</h4>
          <div class="gap">
            <a class="grey foot" href="https://www.facebook.com/">Facebook</a>
          </div>
          <div class="gap">
            <a class="grey foot" href="https://twitter.com/login">Twitter</a>
          </div>
          <div class="gap">
            <a class="grey foot" href="https://www.instagram.com/accounts/login/">Instagram</a>
          </div>
        </div>
        <div class="col-sm-3">
          <img src="{% static 'images/dashboard/logo.png' %}" alt="Shoptastic" class="logo">
        </div>
      </div>
      <hr style="border-color: #37475A">
      <div class="container-fluid">

        <h3 class="white" style="text-align: center;">Shoptastic</h3>
        <div class="row" style="padding-bottom: 10px;">
          <div class="pop end col-sm-1">
            <a href="#" class=" foot grey">India</a>
          </div>
          <div class="pop end col-sm-1">
            <a href="#" class=" foot grey">Australia</a>
          </div>
          <div class="pop end col-sm-1">
            <a href="#" class=" foot grey">Greenland</a>
          </div>
          <div class="pop end col-sm-1">
            <a href="#" class=" foot grey">Brazil</a>
          </div>
          <div class="pop end col-sm-1">
            <a href="#" class="foot grey">Alaska</a>
          </div>
          <div class="pop end col-sm-1">
            <a href="#" class=" foot grey">Singapore</a>
          </div>
          <div class="pop end col-sm-1">
            <a href="#" class=" foot grey">Canada</a>
          </div>
          <div class="pop end col-sm-1">
            <a href="#" class=" foot grey">France</a>
          </div>
          <div class="pop end col-sm-1">
            <a href="#" class=" foot grey">Portugal</a>
          </div>
          <div class="pop end col-sm-1">
            <a href="#" class=" foot grey">Greece</a>
          </div>
          <div class="pop end col-sm-1">
            <a href="#" class=" foot grey">Japan</a>
          </div>
          <div class="pop end col-sm-1">
            <a href="#" class=" foot grey">Maldives</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

</html>